<img src='https://g.gravizo.com/svg?
custom_mark13
@startuml;

participant "Local_Planner" as A;
participant "Bridge" as B;
participant "Motionplanner" as C;
participant "Obstacle_detect" as D;

-> A: Room, StatObst, Global_Costmap;
note left: InitPlanner
activate A;
A -> B: Req: Init, Costmap;
activate B;
B -> D: Req: global_costmap;
activate D;
D --> B: Resp: BasicShape;
deactivate D;
activate C;
B -> C: Room, obst;
deactivate C
B --> A: Resp: None;
deactivate B;
deactivate A;

-> A: Global_Plan;
note left: ConfigPlanner
activate A;
A -> B: Req: Path;
activate B;
B -> C: goal (next waypoint)
note over C: (topic)/trigger
deactivate A;
A -> A: RATE
deactivate B;

activate A;
A -> B: Req: CurrentState(T,t);
activate B;
D --> B: (topic)/DynObst;
B -> C: Req: (topic)/trigger-DynObst;
activate C;
C --> B: Speed_cmd;
deactivate C;
B ->: (topic)/position;
B --> A: Resp: cmd_vel;
deactivate B;
<- A: cmd_vel;
deactivate A;
A -> A: RATE

@enduml
custom_mark13
 }
'/>
