<img src='https://g.gravizo.com/svg?
custom_mark13
@startuml;
actor User;
participant "Local_Planner" as A;
participant "Bridge" as B;
participant "Motionplanner" as C;
participant "Obstacle_detect" as D;

User -> A: Room, StatObst, Global_Costmap;
activate A;
A -> B: Req: Init, Costmap;
activate B;
B -> D: Req: global_costmap;
activate D;
D --> B: Resp: BasicShape;
deactivate D;
activate C;
B -> C: Room, obst;
deactivate C
B --> A: Resp: None;
deactivate B;
deactivate A;

actor User;
User -> A: Global_Plan;
activate A;
A -> B: Req: Path;
activate B;
B -> C: (topic)/trigger;
B -> C: goal (next waypoint);
deactivate B;




A -> B: Req: CurrentState(T,t);
activate D;
D --> B: (topic)/DynObst;
deactivate D;
B -> C: Req: (topic)/trigger-DynObst;
activate C;
C --> B: Speed_cmd;
deactivate C;
B -> User: (topic)/position;
B --> A: Resp: cmd_vel;
A -> User: cmd_vel;
deactivate A;

@enduml
custom_mark13
 }
'/>
