<img src='https://g.gravizo.com/svg?
custom_mark13
@startuml;

participant "Local_Planner" as A;
participant "Bridge" as B;
participant "Motionplanner" as C;
participant "Obstacle_detect" as D;

-> A: Room, StatObst, Global_Costmap;
activate A;
note left: InitPlanner;
A -> B: Req: Init, Costmap;
activate B;
B -> D: Req: global_costmap;
activate D;
D --> B: Resp: BasicShape;
deactivate D;
B -> C: Room, obst;
activate C;
C --> B: Ready
deactivate C;
B --> A: Resp: None;
deactivate B;
deactivate A;

-[#red]> A: Loop 1
-> A: Global_Plan;
note left: ConfigPlanner;
activate A;
A -> B: Req: Path;
activate B;
B -> C: goal (next waypoint);
activate C;
C --> B: Robottrajectory / vel_traj & x & y traj: means ready
deactivate C;
note left: (topic)/trigger;
deactivate A;
deactivate B;

-[#0000FF]> A: Loop 2
activate A;
A -> B: Req: CurrentState(T,t);
activate B;
D <[#green]-: Loop 3
D<-: Local Costmap
activate D;
D --> B: (topic)/DynObst;
deactivate D;
D -[#green]>: Loop 3
B -> C: Req: (topic)/trigger-DynObst;
activate C;
C --> B: Speed_cmd;
deactivate C;
B --> A: Resp: cmd_vel;
deactivate B;
<- A: cmd_vel;
deactivate A;
<[#0000FF]- A: Loop 2
<[#red]- A: Loop 1

@enduml
custom_mark13
 }
'/>
