<img src='https://g.gravizo.com/svg?
custom_mark13
@startuml;

participant "Vel_cmd" as V;
participant "Kalman" as K;

-> K: Pos measurement
note left: **t0**;

-> A: OMG-tools command;
note left: t1;
A -> B: Req: vel_cmd(t1);
activate B;
B -> A: Resp: Xhat(t2)
deactivate B;
activate A;
deactivate A;
A -> B: Req: vel_cmd(t1);


@enduml
custom_mark13
 }
'/>
